modfileVersion: "v1"
id: github.com/SENERGY-Platform/mgw-test-module-b/mgw-module-1
name: MQTT publisher 1
version: v1.0.0
type: add-on
deploymentType: single
serviceReferences:
  publisher2:
    - refVar: P2
      services:
        - publisher
  publisher:
    - refVar: P6
      services:
        - publisher
dependencies:
  github.com/SENERGY-Platform/mgw-test-module-a:
    version: <v2.0.0
    requiredServices:
      server:
        - refVar: MQTT_BROKER
          services:
            - publisher
            - publisher2
  github.com/SENERGY-Platform/mgw-test-module-b/mgw-module-2:
    version: ">=v1.0.0;<v2.0.0"
    requiredServices:
      publisher:
        - refVar: TEST
          services:
            - publisher
  github.com/SENERGY-Platform/mgw-test-module-b/mgw-module-3:
    version: ">=v1.0.0;<v2.0.0"
    requiredServices:
      publisher:
        - refVar: TEST2
          services:
            - publisher
services:
  publisher:
    name: Publisher
    image: ghcr.io/senergy-platform/mgw-test-module-b-publisher:0.0.1
    requiredServices:
      - publisher2
  publisher2:
    name: Publisher2
    image: ghcr.io/senergy-platform/mgw-test-module-b-publisher:0.0.1
configs:
  c1:
    dataType: string
    targets:
      - refVar: C1
        services:
          - publisher
    userInput:
      type: text
      typeOptions:
        regex: ^[a-zA-Z0-9-_]+$
        min_len: 3
        max_len: 15
      name: Config 1
      description: Some text value.
      group: cfg
    optional: true
  c2:
    value:
      - test
    dataType: string
    isList: true
    targets:
      - refVar: C2
        services:
          - publisher
    userInput:
      type: text
      typeOptions:
        regex: ^[a-zA-Z0-9]+$
        max_len: 10
      name: Config 2
      description: List of text values.
      group: cfg
  c3:
    options:
      - a
      - b
      - c
    optionsExt: true
    dataType: string
    isList: true
    targets:
      - refVar: C3
        services:
          - publisher
    userInput:
      type: text
      typeOptions:
        regex: ^[a-z]+$
        max_len: 1
      name: Config 3
      description: The alphabet with duplicates.
      group: cfg
  c4:
    value: 1
    options:
      - 1
      - 2
      - 3
    dataType: int
    targets:
      - refVar: C4
        services:
          - a
    userInput:
      type: number
      name: Config 4
      description: Select alternative option.
      group: cfg
  c5:
    dataType: float
    targets:
      - refVar: C5
        services:
          - publisher
    userInput:
      type: number
      typeOptions:
        min: 1.0
        max: 2.0
        step: 0.1
      name: Config 5
      description: Select from range.
      group: adv
  c6:
    value: 2
    options:
      - 2
      - 3
      - 4
    dataType: int
    targets:
      - refVar: C6
        services:
          - publisher
    userInput:
      type: number
      name: Config 6
      description: Select alternative option.
      group: cfg
inputGroups:
  cfg:
    name: Configuration
    description: Change stuff ...
  res:
    name: Controller
    description: Select host stuff ...
  sec:
    name: Security
    description: Secure stuff ...
    group: adv
  adv:
    name: Advanced Settings
    description: Advanced stuff ...