modfileVersion: "v1"
id: github.com/SENERGY-Platform/mgw-test-module-b/mgw-module-2
name: MQTT publisher 2
version: v1.0.0
type: add-on
deploymentType: single
dependencies:
  github.com/SENERGY-Platform/mgw-test-module-a:
    version: <v3.0.0
    requiredServices:
      server:
        - refVar: MQTT_BROKER
          services:
            - publisher
services:
  publisher:
    name: Publisher
    image: ghcr.io/senergy-platform/mgw-test-module-b-publisher:0.0.1
configs:
  c1:
    dataType: string
    targets:
      - refVar: C1
        services:
          - publisher
    userInput:
      type: text
      typeOptions:
        regex: ^[a-zA-Z0-9-_]+$
        min_len: 3
        max_len: 15
      name: Config 1
      description: Some text value.
      group: cfg
    optional: true
  c2:
    value:
      - test
    dataType: string
    isList: true
    targets:
      - refVar: C2
        services:
          - publisher
    userInput:
      type: text
      typeOptions:
        regex: ^[a-zA-Z0-9]+$
        max_len: 10
      name: Config 2
      description: List of text values.
      group: cfg
inputGroups:
  cfg:
    name: Configuration
    description: Change stuff ...