modfileVersion: "v1"
id: github.com/SENERGY-Platform/mgw-test-module-b/mgw-module-4
name: MQTT publisher 4
version: v3.0.0
type: add-on
deploymentType: single
dependencies:
  github.com/SENERGY-Platform/mgw-test-module-a:
    version: <v3.0.0
    requiredServices:
      server:
        - refVar: MQTT_BROKER
          services:
            - publisher
services:
  publisher:
    name: Publisher
    image: ghcr.io/senergy-platform/mgw-test-module-b-publisher:0.0.1
hostResources:
  h1:
    targets:
      - mountPoint: /dev/testUSBTTy
        services:
          - publisher
    userInput:
      name: Device 1
      description: Some device.
      group: cfg
secrets:
  s1:
    type: basic-auth
    targets:
      - mountPoint: /opt/user
        item: username
        services:
          - publisher
      - mountPoint: /opt/pw
        item: password
        services:
          - publisher
      - refVar: USER_SEC
        item: username
        services:
          - publisher
      - refVar: PW_SEC
        item: password
        services:
          - publisher
    userInput:
      name: Secret 1
      description: Some secret.
      group: cfg
configs:
  c1:
    options:
      - a
      - b
      - c
    optionsExt: true
    dataType: string
    isList: true
    targets:
      - refVar: C1
        services:
          - publisher
    userInput:
      type: text
      typeOptions:
        regex: ^[a-z]+$
        max_len: 1
      name: Config 1
      description: The alphabet with duplicates.
      group: cfg
inputGroups:
  cfg:
    name: Configuration
    description: Change stuff ...