modfileVersion: "v1"
id: github.com/SENERGY-Platform/mgw-test-module-b/mgw-module-6
name: MQTT publisher 6
version: v0.0.1
type: add-on
deploymentType: single
dependencies:
  github.com/SENERGY-Platform/mgw-test-module-a:
    version: <v3.0.0
    requiredServices:
      server:
        - refVar: MQTT_BROKER
          services:
            - publisher
services:
  publisher:
    name: Publisher
    image: ghcr.io/senergy-platform/mgw-test-module-b-publisher:0.0.1
configs:
  c1:
    options:
      - a
      - b
      - c
    optionsExt: true
    type: text
    typeOptions:
      regex: ^[a-z]+$
      max_len: 1
    dataType: string
    isList: true
    targets:
      - refVar: C3
        services:
          - publisher
    userInput:
      name: Config 3
      description: The alphabet with duplicates.
      group: cfg
inputGroups:
  cfg:
    name: Configuration
    description: Change stuff ...