modfileVersion: "v1"
id: github.com/SENERGY-Platform/mgw-test-module-b/mgw-module-5
name: MQTT publisher 5
version: v2.0.1
type: add-on
deploymentType: single
dependencies:
  github.com/SENERGY-Platform/mgw-test-module-a:
    version: <v3.0.0
    requiredServices:
      server:
        - refVar: MQTT_BROKER
          services:
            - publisher
services:
  publisher:
    name: Publisher
    image: ghcr.io/senergy-platform/mgw-test-module-b-publisher:0.0.1
secrets:
  s1:
    type: basic-auth
    targets:
      - mountPoint: /opt/user
        item: username
        services:
          - publisher
      - mountPoint: /opt/pw
        item: password
        services:
          - publisher
      - refVar: USER_SEC
        item: username
        services:
          - publisher
      - refVar: PW_SEC
        item: password
        services:
          - publisher
    userInput:
      name: Basic Auth
      description: Basic auth test.
      group: cfg
  s2:
    type: api-key
    targets:
      - mountPoint: /opt/key
        services:
          - publisher
      - refVar: API_KEY_SEC
        services:
          - publisher
    userInput:
      name: API Key
      description: API key test.
      group: cfg
  s3:
    type: certificate
    targets:
      - mountPoint: /opt/cert.crt
        services:
          - publisher
      - refVar: CERT_SEC
        services:
          - publisher
    userInput:
      name: Certificate
      description: certificate test.
      group: cfg
inputGroups:
  cfg:
    name: Configuration
    description: Change stuff ...