modfileVersion: "v1"
id: github.com/SENERGY-Platform/mgw-test-module-b/mgw-module
name: MQTT publisher
version: v0.1.4
type: add-on
deploymentType: single
serviceReferences:
  publisher2:
    - refVar: P2
      services:
        - publisher
  publisher6:
    - refVar: P6
      services:
        - publisher
dependencies:
  github.com/SENERGY-Platform/mgw-test-module-a:
    version: <v3.0.0
    requiredServices:
      server:
        - refVar: MQTT_BROKER
          services:
            - publisher
            - publisher2
  github.com/SENERGY-Platform/mgw-test-module-b/mgw-module-2:
    version: ">=v0.0.1;<v1.0.0"
    requiredServices:
      publisher:
        - refVar: TEST
          services:
            - publisher
  github.com/SENERGY-Platform/mgw-test-module-b/mgw-module-6:
    version: ">=v0.0.1;<v1.0.0"
    requiredServices:
      publisher:
        - refVar: TEST
          services:
            - publisher
services:
  publisher:
    name: Publisher
    image: ghcr.io/senergy-platform/mgw-test-module-b-publisher:0.0.1
    requiredServices:
      - publisher2
  publisher2:
    name: Publisher2
    image: ghcr.io/senergy-platform/mgw-test-module-b-publisher:0.0.1
configs:
  c1:
    type: text
    typeOptions:
      regex: ^[a-zA-Z0-9-_]+$
      min_len: 3
      max_len: 15
    dataType: string
    targets:
      - refVar: C1
        services:
          - publisher
    userInput:
      name: Config 1
      description: Some text value.
      group: cfg
    optional: true
  c2:
    value:
      - test
    type: text
    typeOptions:
      regex: ^[a-zA-Z0-9]+$
      max_len: 10
    dataType: string
    isList: true
    targets:
      - refVar: C2
        services:
          - publisher
    userInput:
      name: Config 2
      description: List of text values.
      group: cfg
  c3:
    options:
      - a
      - b
      - c
    optionsExt: true
    type: text
    typeOptions:
      regex: ^[a-z]+$
      max_len: 1
    dataType: string
    isList: true
    targets:
      - refVar: C3
        services:
          - publisher
    userInput:
      name: Config 3
      description: The alphabet with duplicates.
      group: cfg
  c5:
    type: number
    typeOptions:
      min: 1.0
      max: 2.0
      step: 0.1
    dataType: float
    targets:
      - refVar: C5
        services:
          - publisher
    userInput:
      name: Config 5
      description: Select from range.
      group: adv
  c6:
    value: 2
    options:
      - 2
      - 3
      - 4
    type: number
    dataType: int
    targets:
      - refVar: C6
        services:
          - publisher
    userInput:
      name: Config 6
      description: Select alternative option.
      group: cfg
inputGroups:
  cfg:
    name: Configuration
    description: Change stuff ...
  res:
    name: Controller
    description: Select host stuff ...
  sec:
    name: Security
    description: Secure stuff ...
    group: adv
  adv:
    name: Advanced Settings
    description: Advanced stuff ...