modfileVersion: "v1"
id: github.com/SENERGY-Platform/mgw-test-module-b/mgw-module
name: MQTT publisher
version: v0.0.5
type: add-on
deploymentType: single
dependencies:
  github.com/SENERGY-Platform/mgw-test-module-a:
    version: =v0.0.1
    requiredServices:
      server:
        - refVar: MQTT_BROKER
          services:
            - publisher
services:
  publisher:
    name: Publisher
    image: ghcr.io/senergy-platform/mgw-test-module-b-publisher:0.0.1
