modfileVersion: "v1"
id: github.com/SENERGY-Platform/mgw-test-module-b/mgw-module
name: MQTT publisher
version: v0.0.4
type: add-on
deploymentType: single
dependencies:
  github.com/SENERGY-Platform/mgw-test-module-a:
    version: =v0.0.2
    requiredServices:
      server:
        - refVar: MQTT_BROKER
          services:
            - publisher
services:
  publisher:
    name: Publisher
    image: publisher:local
