modfileVersion: "v1"
id: github.com/SENERGY-Platform/mgw-test-module-b
name: MQTT publisher
version: v0.0.1
type: add-on
deploymentType: single
dependencies:
  test.com/test/mosquitto:
    version: =v0.0.1
    requiredServices:
      server:
        - refVar: MQTT_BROKER
          services:
            - publisher
services:
  publisher:
    name: Publisher
    image: publisher:local
